### PR TITLE
optical_size.textproto Title Case for consistency

### PR DESCRIPTION
**Pull request by davelab6**
M3 uses Title Case for axis names as they are Proper Nouns, we should be consistent.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Need to update expected values to pass CI

**Comment by chrissimpkins** [comment]
It looks like at least one of the test families needs a STAT table update?  @m4rc1e thoughts?

**Comment by davelab6** [comment]
We won't touch flex as it's a whole project to push it. Can we add an Allowlist of exceptions to the CI, add an issue to Flex to fix this next time we update it, and merge this if that's the only one?

**Comment by chrissimpkins** [comment]
Believe that it is only used as a test file.  I think that only the test file(s) in this repo requires the update.

https://github.com/googlefonts/axisregistry/tree/main/tests/data

**Comment by davelab6** [comment]
Sounds good, ttx hotfix will be fine

**Comment by davelab6** [comment]
Done

**Comment by chrissimpkins** [comment]
https://github.com/google/fonts/pull/5704

**Pull request merged**
