### PR TITLE
Update optical_size.textproto for Playfair, from 6..144 to 5..1200

### PR DESCRIPTION
**Pull request by davelab6**
For consideration by @evanwadams :)

### CODE REVIEW

**Comment by RosaWagner** [comment]
@evanwadams validated in group chat to the condition of that we have a hard rule of no addition of fallbacks between 144…1200

**Comment by chrissimpkins** [comment]
Do we have an example use case for 1200pt optical size?

**Comment by RosaWagner** [comment]
I am sure @clauseggers can answer that directly.

**Comment by clauseggers** [comment]
I’m under the weather so not firing on all cylinders atm. However, I assume your sliders are linear (?), whereas some typographical axes as exponential/logarithmic. The optical size axis in Playfair is one such axis. In the Playfair repo there is an Apple Numbers [Optical Size instances.numbers](https://github.com/clauseggers/Playfair/blob/master/sources/Optical%20Size%20instances.numbers) where you can both read and see these shenanigans.

**Pull request merged**
