### PR TITLE
Add custom axis for Irregularity (IRGL)

### PR DESCRIPTION
**Pull request by arrowtype**
PR to follow up on the inclusion of the new custom axis Irregularity, `IRGL`: https://github.com/googlefonts/axisregistry/issues/37

Required for the upcoming release of [Shantell Sans](https://next--shantell-sans.netlify.app/).

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Shantell Sans tracker https://github.com/google/fonts/issues/4465

**Comment by arrowtype** [comment]
@vv-monsalve sorry, what revision would be required for the fallbacks? I don’t see any comments, but I may be missing something. Thanks for taking a look!

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/axisregistry/pull/63#issuecomment-1226514246

**Comment by RosaWagner** [comment]
To follow up on the conversation about the "irregular" axis that we started in the meeting last week. I would like to suggest a "Formal" axis, which can follow some level of language. In French we have: Familiar, Common and Formal. I guess for Shantell Sans, the range would be [-100, 0] in that case.

**Comment by vv-monsalve** [comment]
Following up on that conversation we considered: Vivid, Lively, Energy, Informal (which would be one of the extremes of the `Formal` option), and Relax and.

- **Vivid** and **Lively** were taken from already common words to refer to letters from calligraphic traditions and script fonts to refer to more vibrant and "careless" traces, therefore less 'regular' shapes.
- **Energy** was suggested following the above but was thought it could suggest slanted shapes, which Shantell hasn't.
- **Informal** was considered as another way to imply "irregular" in a more typographic way. But @thundernixon said Shantell was overall informal.
- **Relax** was then proposed as another alternative.

To prevent the discussion from going into too much nuances which could make it endless, is important to remember that the idea would be to find a concept that 
- Avoids possible not so possitive associations (like the ones "Irregularity" could have plus some possible confussions `FamilyName)
- Keep the end-user at the center of decisions and prefer user-friendly names that could transmit the effect of the axis in the font rather than too technically specific ones.
- The axis name and range could be reusable. But specially considering that each term will have enough consensus on concept but could mean something different on each font. In the same way a `Medium` could do it for each particular font family. E.g. Energy could evoke all sorts of different things.

**Comment by arrowtype** [comment]
> I guess for Shantell Sans, the range would be [-100, 0] in that case.

@RosaWagner are you suggesting that the full range of the "Formal" axis would be -100 to +100? If so, I suppose this naming could be logical. 

At least in the way that I’ve heard "formal" vs "informal" used before, I understood it to mean that a "formal" font was one with traditional styling, mostly meant for reading, while an "informal" font was one with inventive or non-traditional styling, mostly meant to grab the viewer’s attention. 

In that framework, Shantell Sans Normal is "mostly informal" and Shantell Sans Irregular is "extra informal."

This webpage isn’t really a perfect resource, but it’s the first Google result for "formal and informal fonts", and it matches my overall impression of the terms:

https://sarahesparrow.wordpress.com/2014/02/26/typography-formal-vs-informal/

Other sources will contrast "formal scripts" and "informal scripts," with formal being things like Bickham Script, and casual being things like Brush Script. 

> Formal Scripts: These typefaces are derived from 17th century formal writing styles.
> Casual Scripts: These typefaces are designed to suggest informality, as if they were written quickly

https://www.fonts.com/content/learning/fontology/level-1/type-anatomy/type-classifications

On that note, I suppose I could imagine an "informal" axis that could take a variable font from a high-contrast, elegant "Bickham Script" to a lower-contrast, energetic "Brush Script."

And somehow, "informal" sounds like it could be slightly more fitting to Shantell Sans. The informal=0 side would still be a lot less formal than 17th-century scripts, but it makes intuitive sense that Shantell Sans could have an axis to amp up its informality.

**Comment by arrowtype** [comment]
I suppose one strength "Formal" has over "Informal" is that it has a more obvious abbreviation. `FRML` is relatively simple to guess at the meaning of, whereas `IFRM` or `IFML` are less obvious. It’s hard to know if this should really be a strong consideration, though. Outside of CSS and file names, how often do end users really see the tags?

**Comment by arrowtype** [comment]
By the way, despite my "bike shedding" comment, I do genuinely appreciate having a process to help make sure that axes have the best possible naming, and I appreciate the team for helping out here! My fear is that the process could lead to defining overly-broad axes, in a desire to overly standardize things that don’t necessarily benefit from a high level of standardization.

**Comment by vv-monsalve** [comment]
Formal and Informal concepts have some sort of tradition in script fonts where they are used to indicate how graceful or loose they are (from the 'regularity' of the trace to convey different meanings like elegance or friendly).

https://www.fonts.com/content/learning/fyti/typefaces/scripts
Myfonts script+formal https://www.myfonts.com/collections/tags/formal+script-fonts
Myfonts script+informal https://www.myfonts.com/collections/tags/informal+script-fonts

Indeed "Informal" is often referred to as "casual" actually, it would be the ideal term. But, as we've discussed, we can't use the already registered `Casual` axis for it due to the way it was originally registered. 

The above relates to the "bike shedding" comment. We are working now on the protocol that will define the requisites (and logic behind them) and steps needed to register a new axis precisely to prevent both situations: an axis that can't be used on other projects + making the registering process too long.

> I would expect that font to choose the axis that was additive, and went from a default to the not-default.

Agreed. I think it would make more sense in most cases for a font to go from a default "formal" to an "informal" variation (similar to what happens in the weight axis going from "Regular" to anything else).

> Informality because it sounds typographic, wouldn’t be confused with the "Regular" weight, and is a thing that could be added to a script or other font.

Agreed, from above points. I wouldn't prioritize the tag to prefer an axis name. `ShantellSans[BNCE,INFR,wght].ttf` with a `ShantellSans_SemiBouncy_Informal-Regular.ttf` companion would make sense.

**Comment by vv-monsalve** [comment]
> Of course, this may imply that the reverse axes should exist in families that have the reverse conceptual focus. I could imagine a "sharp" font that gets even sharper, in which case the "Soft" axis would seem silly. For the most part, I don’t really think there is a drawback to having these two axes coexist. They are "custom" axes, meant to allow new, creative ideas to be made. The only slight problem would be if two fonts were to use the same axes name, but have completely different meaning or value ranges.

> Even if a font had an extremely wide axis that went from very sharp to sharp to soft to very soft, I would expect that font to choose the axis that was additive, and went from a default to the not-default. So, if "sharp" was the default, it would probably make sense to use the "soft" axis, so users could add softness when desired. Or, if "soft" was the default, a "sharp" axis would make sense to add in "sharpness."

This is why we didn't use `SOFT` for Geologica, despite the `Sharp` location in it. 

We are actually debating around these reasonings to include a `ROND` + `SHARP` axes. The tricky part comes when considering cases that could go "Sharp-"Flat"(regular)-Rond"

cc @davelab6 and @evanwadams

**Comment by vv-monsalve** [comment]
The name of the axis could be the noun `Informality` which by concept will cover `Formal` and `Informal` positions.
Similar to the "Softness" axis.

**Comment by arrowtype** [comment]
Yeah, I think that seems pretty solid. I suppose `INFR` might be a decent abbreviation?

**Comment by vv-monsalve** [comment]
> I suppose `INFR` might be a decent abbreviation?

I'd say yes.

**Comment by vv-monsalve** [comment]
Informality axis definitions draft:

```
tag: "INFR"
display_name: "Informality"
min_value: 0
default_value: 0
max_value: 100.0
precision: -1
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "Adjust glyph shapes from normalized proportions to irregular shaping and sizing. "
  "Intended especially for handwriting-themed fonts which seek to provide "
  "a range of from highly readable to highly expressive."
```

**Comment by vv-monsalve** [comment]
@davelab6 @evanwadams 
This is the axis proposal built from Irregularity revision (and if we definitely can't change `Casual` axis in the short term).
Would you please give it a review, comments, or approval?

**Comment by vv-monsalve** [comment]
On a private conversation @thundernixon suggested changing the tag to `INFM` to avoid confusion with inferior numbers

**Comment by arrowtype** [comment]
The current description is a little too narrow to one project:
> Adjust glyph shapes from normalized proportions to irregular shaping and sizing. Intended especially for handwriting-themed fonts which seek to provide a range from highly readable to highly expressive.

Proposed description:
> Adjust overall glyph shaping and design from traditional to inventive. Intended especially for fonts which seek to provide a stylistic range from highly readable to highly expressive.

**Comment by vv-monsalve** [comment]
Followed on #90

**Pull request closed without merging**
