### PR TITLE
Add Bounce [BNCE] axis

### PR DESCRIPTION
**Pull request by arrowtype**
PR to follow up on the inclusion of the new custom axis Bounce, `BNCE`. https://github.com/googlefonts/axisregistry/issues/38

Required for the upcoming release of [Shantell Sans](https://next--shantell-sans.netlify.app).

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Shantell Sans tracker: https://github.com/google/fonts/issues/4465

**Comment by arrowtype** [comment]
@vv-monsalve sorry, what revision would be required for the fallbacks? I don’t see any comments, but I may be missing something. Thanks for taking a look!

**Comment by chrissimpkins** [comment]
We're still finalizing details.  The current plan is to define one fallback position named "Default" that is defined at the default axis value.  Shouldn't be anything to do on your end.  We can add the field when we are ready to merge.  Docs will be coming as the axis registration process stabilizes.  Thanks!

**Comment by arrowtype** [comment]
Excellent, thank you for the explanation, @chrissimpkins! That sounds good. I'll be in touch with a font PR in a week or two, if all goes well, and we can discuss things further there, as needed. Thanks again!

**Comment by chrissimpkins** [comment]
Will queue up the Shantell Sans axes for discussion at our next axis registration meeting.  Thanks Stephen!

**Comment by chrissimpkins** [comment]
Will the first version of Shantell Sans include all three new axes?

**Comment by arrowtype** [comment]
Yup! If we can get all the axes defined, then it will. Weight, Italic, Bounce, Irregularity, and Tracking/Spacing:

kinetic

**Comment by vv-monsalve** [comment]
@arrowtype as said by Chris we are now reviewing all the incoming axes and everything will be included in docs. This is why I didn't include details on the added label yet. Thank you for the added images; they are helpful to see the axes working.

**Comment by vv-monsalve** [comment]
@arrowtype from our today's conversation, I've updated the .textproto file

**Comment by arrowtype** [comment]
Amazing, thank you, @vv-monsalve! This is looking great to me.

**Review by davelab6 — APPROVED** [review]

**Review by davelab6 — APPROVED** [review]

**Comment by vv-monsalve** [comment]
The description was updated following the meeting's decisions.

**Pull request merged**
