### PR TITLE
Add Spacing [SPAC] axis

### PR DESCRIPTION
**Pull request by arrowtype**
Addresses https://github.com/googlefonts/axisregistry/issues/27

I’ve done my best to describe this axis in a way that is specific but also leaves some room for interpretation by designers.

I need this axis to be adopted for the soon-to-be-released [Shantell Sans](http://next--shantell-sans.netlify.app), so if others believes my definition could be improved, I would appreciate any specific suggestions of better definitions.

## My main question: 

How do we handle ranges when there is no inherent min/max?

There is no inherent "minimum" or "maximum" value for a Tracking axis ... if the value is interpreted as plus or minus units on a 1000 UPM grid, then perhaps the range could be -1000 to 1000, or maybe even greater. The current PR uses `0` to `500` as that is what Shantell Sans uses, but I do not believe this should be the full potential range for any given project.

Thanks for any feedback that helps move this forward!

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Shantell Sans https://github.com/google/fonts/issues/4465

**Comment by arrowtype** [comment]
@davelab6 should this PR be changed to the name "spacing"?

**Comment by vv-monsalve** [comment]
> if the value is interpreted as plus or minus units on a 1000 UPM grid, then perhaps the range could be -1000 to 1000, or maybe even greater.

When the axis value is related to some measure of the font, then a "per thousand em" range, 0..1000, is preferred indeed.
@davelab6

**Comment by vv-monsalve** [comment]
> @davelab6 should this axis and PR be changed to the name "spacing"? ([#27 (comment)](https://github.com/googlefonts/axisregistry/issues/27#issuecomment-1218298209))

@thundernixon From Dave and Evan's comment in an internal document, the answer is yes

**Comment by davelab6** [comment]
Updated to latest draft

**Review by davelab6 — APPROVED** [review]

**Comment by vv-monsalve** [comment]
Description was updated following the meeting's decisions.

**Pull request merged**
